### ISSUE TITLE
Workspace defaulted to readonly directory on Windows

### ISSUE THREAD

**Issue by viosoft** [mips-open-ide/Releases#1]
I stumbled over a couple of issues right from the start on a Windows 10 system:
When running the IDE installed I am getting the following message:

Windows 10 does not want to let the workspace reside under the C:/Program Files/ folder.

I have created a workspace folder under my user id sub-directory in the Users folder of Windows 10.

-- From Dinu

**Comment by tuanha-viosoft** [comment]
> I stumbled over a couple of issues right from the start on a Windows 10 system:
>When running the IDE installed I am getting the following message:
>
>Windows 10 does not want to let the workspace reside under the C:/Program Files/ folder.

Yes, this is an issue happened on Windows 10. It doesn't allow us to create folder inside Program Files without administration.
We changed the default workspace to user folder in Windows.
This issue is fixed in the release v1.0.20190324.
https://github.com/mips-open-ide/Releases
