### ISSUE TITLE
Installation issue continues. (Issue #8 closed too soon)

### ISSUE THREAD

**Issue by dradian** [mips-open-ide/Releases#10]
I have downloaded the MTI toolchain untarred to a different location (see MissingMTIToolchain.png).
![MIssingMTIToolchain](https://user-images.githubusercontent.com/643539/55105985-0a993600-508b-11e9-9df9-cc54d4081c7b.png)

Then I have modified the Path as shown in the New PATH environment variable.png

![New PATH environment variable](https://user-images.githubusercontent.com/643539/55105974-ff460a80-508a-11e9-80f1-1a3b13b8c0ae.png)

I restarted the system, launched MIPS Open IDE from the desktop icon and observed the same MissingToolchain.png message as before. When pressing the close button, the MIPS Open IDE app closes as well.

The problem was reproduced on Windows 7 Pro. 
CONCLUSION: To remedy this problem, it seems we need to install and include in the path not only the MTI Bare Metal Toolchain, but also the MTI GNU/Linux Toolchain. This in not clearly stated in the "Missing Toolchains" message box, and not in the Release Notes.

IMPORTANT NOTE: If only MTI Toolchain builds are supported by the tool, then users may become confused as to which toolchain to download. Suggestion: either indicate this in the Missing Toolchains.png message box, or in the Release Notes for MIPS Open IDE, or remove the choices which are not compatible with MIPS Open IDE form the URL link which is provided in the Missing Toolchains.png message.

REMINDER NOTE: As mentioned before, having an uninstaller for the application is standard.

**Comment by dzungdh-viosoft** [comment]
@dradian please help to add your MTI toolchain location to the System Variables PATH, not User variables PATH.
For uninstaller of the application, we're working on it and will be included in next release.

**Comment by kurt-wave** [comment]
Hi Dinu,
The link in the missing toolchain dialog sends you to a MIPS website.  That is OUR download page, it is not maintained by Viosoft.  I think all that is needed here is a note on the dialog with the link that says something like this: Go to this page and download just the mips-mti-* versions of the toolchain.  The users of MIPS Open should be OK with that I think.

**Comment by tuanha-viosoft** [comment]
> The link in the missing toolchain dialog sends you to a MIPS website. That is OUR download page, it is not maintained by Viosoft. I think all that is needed here is a note on the dialog with the link that says something like this: Go to this page and download just the mips-mti-* versions of the toolchain. The users of MIPS Open should be OK with that I think.

All 4 toolchains are supported in the release v1.0.20190402. Please try it.

> REMINDER NOTE: As mentioned before, having an uninstaller for the application is standard.

The uninstaller will be added soon.

**Comment by tuanha-viosoft** [comment]
> The uninstaller will be added soon.

The uninstaller is added in v1.0.20190403
