### ISSUE TITLE
Besides MIPS Open IDE and the MIPS toolchains installed, the user of Windows system needs to install other utilities 

### ISSUE THREAD

**Issue by dradian** [mips-open-ide/Releases#11]
After successful installation of MIPS Open IDE, and of the MTI toolchains, the user of a Windows system needs to install other utilities (for ex. make) for the development environment in order to be able to successfully use MIPS Open IDE.
Without such utilities trying for example to build the simplest application will fail.
Such a tool is MinGW from mingw.org. 

I did not find this requirement indicated in the documentation provided with MIPS Open IDE.

**Comment by viosoft** [comment]
This is documented here: https://github.com/mips-open-ide/Releases/wiki/Installing-host-tools
