### ISSUE TITLE
Standalone embedded program does not terminate correctly

### ISSUE THREAD

**Issue by kurt-wave** [mips-open-ide/Releases#14]
**Description**
When debugging a standalone embedded program, it does not terminate correctly.  Instead of exiting, the program just loops forever at the end.
This is on Windows 7.

**Steps to reproduce the issue:**
1.  Build a simple standalone embedded project.
2.  Launch it in the debugger.  Click the Resume button so the program runs to the end.
3.  Notice the endless loop.
![image](https://user-images.githubusercontent.com/48976304/55137329-ed498380-50ed-11e9-8d69-498e18412ec1.png)

**Additional information you deem important (e.g. issue happens only occasionally):**
I debugged this a bit, and here is what I found.  If you single step the program beyond the last line of the C program (this is in crt0.S), you go through _exit, then __exit, which does a syscall.  The syscall exception leads you eventually to ___uhi_indirect.  Shortly after that you get to an opcode that the disassembler does not recognize.  But the opcode is actually SDBBP:
![image](https://user-images.githubusercontent.com/48976304/55136766-837caa00-50ec-11e9-99fc-52ebc44166fe.png)

When you step this instruction, the infinite looping occurs.  The Pause button has no effect after that.
![image](https://user-images.githubusercontent.com/48976304/55136837-adce6780-50ec-11e9-876b-927525670616.png)

At this point I am able to terminate and remove the debug launch.  But QEMU does not exit, and when you try to terminate by clicking the red X, you get the Windows "not responding" dialog.
![image](https://user-images.githubusercontent.com/48976304/55137151-714f3b80-50ed-11e9-8fb9-46e791cdf353.png)

So I just close the program.

I'm pretty sure that the SDBBP is how Codescape Debugger traps the end of the program, and then knows to terminate it.  This may be documented in the MIPS_Toolchain_Codescape_GNU_Tools_for_MIPS_Programmers_Guide_1.1.97.pdf, which I have attached.  Check the sections that talk about UHI, which is the semihosting mechanism.

I hope this information helps.

Kurt
[MIPS_Toolchain_Codescape_GNU_Tools_for_MIPS_Programmers_Guide_1.1.97.pdf](https://github.com/mips-open-ide/Releases/files/3016628/MIPS_Toolchain_Codescape_GNU_Tools_for_MIPS_Programmers_Guide_1.1.97.pdf)

**Comment by tuanha-viosoft** [comment]
This issue only happens in Windows. It was fixed in the release v1.0.20190403.
