### ISSUE TITLE
After install, get Program Compatibility Assistant dialog

### ISSUE THREAD

**Issue by kurt-wave** [mips-open-ide/Releases#15]
Immediately after installing the IDE on Windows 7, you get this pop-up:
![image](https://user-images.githubusercontent.com/48976304/55137883-61d0f200-50ef-11e9-8adf-7d737cf20a75.png)

I just click the red X, and the program seems to work OK.  But this warning looks pretty confusing, and I hope it can be fixed.  Thanks!

Kurt

**Comment by tuanha-viosoft** [comment]
This issue is fixed in v1.0.20190403.
