### ISSUE TITLE
Debug Launch Startup specifies big endian even though little endian elf file is selected

### ISSUE THREAD

**Issue by kurt-wave** [mips-open-ide/Releases#18]
I created a MIPS Standalone Embedded Project (Executable).  By default, this program is built as little endian.  I am also aware that the standalone (mips-mti-elf) toolchain support in the MIPS Open IDE is only for little endian.

I then build the little endian elf program in this project, and select the elf file before creating a new debug launch configuration.  I expect the debug launch to also be set up for little endian.  But in the Startup tab of the debug launch configuration, the initialization command is "set endian big"

![image](https://user-images.githubusercontent.com/48976304/55350094-20826e80-5470-11e9-94e4-0b0412402193.png)

I would have expected this to automatically be "set endian little" since I selected a little endian elf file before creating the debug launch.  Is it possible to make this happen?

Kurt

**Comment by tuanha-viosoft** [comment]
Hi Kurt @kurt-wave 

> I created a MIPS Standalone Embedded Project (Executable). By default, this program is built as little endian. I am also aware that the standalone (mips-mti-elf) toolchain support in the MIPS Open IDE is only for little endian.

This is the limitation of this version. In the current release, we allow user to change build configuration to build r2,r6,big or little endian as he wants.

> I would have expected this to automatically be "set endian little" since I selected a little endian elf file before creating the debug launch. Is it possible to make this happen?

We will try to do it, but maybe in next release. Currently, please change endian manually, or you just need to click on Debug button, do not create Debug Configuration manually, and the product will select the right endian for debugging binary.

Tuan Hoang

**Comment by kurt-wave** [comment]
> This is the limitation of this version. In the current release, we allow user to change build configuration to build r2,r6,big or little endian as he wants.

Sorry, I did not mean to imply that the little-endian-only support is a problem.  I was just saying that I understood that the current version is limited to little endian support only.  That's OK, I'm not reporting this as a problem.

> We will try to do it, but maybe in next release. Currently, please change endian manually, or you just need to click on Debug button, do not create Debug Configuration manually, and the product will select the right endian for debugging binary.

I didn't realize that I could just click on the Debug button.  All this time I thought I had to create a debug configuration first.  I tried clicking the Debug button and it worked just as you said.  My debug session was correctly set for little endian and I didn't have to set it manually.  So I take back my complaint in this ticket.  This is actually more of a user misunderstanding on my part.  The enhancement that I asked for would be OK if you can do it, but I no longer consider it to be necessary.  Thanks.

**Comment by tuanha-viosoft** [comment]
> We will try to do it, but maybe in next release. Currently, please change endian manually, or you just need to click on Debug button, do not create Debug Configuration manually, and the product will select the right endian for debugging binary.

The endian is set automatically when creating new Debug Configuration in the release v1.0.20190402.
