### ISSUE TITLE
Register and Variable views do not obey preferred number format

### ISSUE THREAD

**Issue by richardhilbig** [mips-open-ide/Releases#19]
Set preferred number format to hex in the Windows/Preferences/C-C++/Debug section and restart IDE. Debug any program and view the register and variable views. They are in decimal instead of hex. This is probably a CDT bug. It is possible to set each register or variable one at time into a different format but that is not ideal.

![image](https://user-images.githubusercontent.com/48995747/55570283-f4f1c500-56b7-11e9-9938-30127f628f52.png)

**Comment by tuanha-viosoft** [comment]
Hi @richardhilbig 
I think that you used the old version of MIPS Open IDE. Please download the latest version v1.0.20190403

In this version, the IDE preferences has been changed.
![image](https://user-images.githubusercontent.com/17974406/55604654-0cee4500-579b-11e9-8857-6aa38a95bdcc.png)

![image](https://user-images.githubusercontent.com/17974406/55604704-55a5fe00-579b-11e9-9130-5d621250cc97.png)

For Registers and Variables, you can click on each values to see it in multiple formats.

![image](https://user-images.githubusercontent.com/17974406/55604757-a0277a80-579b-11e9-8ac3-65f6fcff5d55.png)
![image](https://user-images.githubusercontent.com/17974406/55604770-b0d7f080-579b-11e9-9f0c-886fa9c4d94c.png)
