### ISSUE TITLE
Problem connecting MIPS toolchain to the IDE 

### ISSUE THREAD

**Issue by viosoft** [mips-open-ide/Releases#2]
After clicking the Web Resources button and requesting the download of a specific MIPS toolchain, The toolchain files are downloaded under the Downloads sub-directory of my user id folder

Looks like the tar file gets and addition .tar extension. (?)

After untarring the toolchain file in a sub-directory called Toolchain, also under user id folder, the IDE and the toolchain are disconnected. How does one connect the toolchain to the IDE?

I have tried to use the Properties option from the File Menu, to no avail. Nothing happens when I click on Properties (?)

Nothing regarding the path for the toolchain seems to be available in the Preferences dialog box under the Windows Menu.

-- From Dinu

**Comment by tuanha-viosoft** [comment]
#4

**Comment by tuanha-viosoft** [comment]
You can extract toolchain anywhere and set PATH environment. Then MIPS Open IDE will detect toolchain automatically. #4
