### ISSUE TITLE
This QEMU requires libpng12, which is not on Ubuntu 18.10

### ISSUE THREAD

**Issue by kurt-wave** [mips-open-ide/Releases#20]
I installed the MIPS Open IDE on a Ubuntu 18,.10 machine.  When I try to start QEMU, I get an error.  I determined that the QEMU in the IDE requires version 12 of libpng.  But version 12 of libpng is no longer available in Ubuntu 16.10+.  My Ubuntu 18.10 machine has version 16 of libpng.

To make the QEMU work, I had to download and install version 12 of libpng onto my Ubuntu machine.

Can this be fixed so the user does not have to install an old version of libpng onto Ubuntu 18.10?

**Comment by tuanha-viosoft** [comment]
Yes, we knew about this error. Currently, we are creating a version for CentOs, and we will add the fix for it in this release. 



Vào ngày 9 thg 4, 2019, lúc 06:45, Kurt Martin <notifications@github.com> đã viết:

**Comment by tuanha-viosoft** [comment]
Fix in the release v1.0.20190409.
