### ISSUE TITLE
Does the Busblaster is support? 

### ISSUE THREAD

**Issue by arbing2014** [mips-open-ide/Releases#21]
Hi All,

It is great to have the MIPS Open IDE. Thanks for your efforts. 

Now, I just want to understand which hardware probe supported?  Does the "Bus-blaster V3C" supported now?  The reason why I ask this is because, some time we need to debug a real EVM board, So need to support the some low cost probe. as Bus-Blaster. 

![httpsstatics3 seeedstudio comimages1109904451](https://user-images.githubusercontent.com/6646354/57347154-df266280-7183-11e9-8469-75e6a81a7abf.jpg)

Thank you so much.

**Comment by viosoft** [comment]
Can you provide links to the MIPS platform / probe combo that you're currently using?  If they're commercially available, we'll provide support in coming releases of the IDE.

**Comment by arbing2014** [comment]
Thank you for your reply.  Please find the MIPS support pages for the Bus-Blaster...

https://www.mips.com/develop/tools/mips-debug-and-trace-probes/bus-blaster

**Comment by viosoft** [comment]
This is now supported.   Closing issue.
