### ISSUE TITLE
Can not choose the "hardware debug"

### ISSUE THREAD

**Issue by arbing2014** [mips-open-ide/Releases#22]
Hi All,

When trying to try the “Hardware debug plug in” to debug via the Probe+Target, We find: 
Although the “Eclipse GDB Hardware Debug core Plug-in” and “Eclipse GDB Hardware Debug UI Plug-in” is installed.  
![P1](https://user-images.githubusercontent.com/6646354/57346386-dda76b00-7180-11e9-9e72-bf968dfa9ac2.jpg)

However, in the “Debug Configurations”, We Can NOT change the debugger to “hardware debug”, Can Only use default QEMU Option.  
![P2](https://user-images.githubusercontent.com/6646354/57346405-f3b52b80-7180-11e9-8bb7-f65938b8672e.png)

Can you please suggest how to choose the hardware debugger?

**Comment by tuanha-viosoft** [comment]
@arbing2014 The real hardware debugger is not supported now.
We will support it later

**Comment by arbing2014** [comment]
Can you please share any schedule on this?

**Comment by tuanha-viosoft** [comment]
@arbing2014 We are dealing with a big update for FreeRTOS objects view now. We will support hardware debug later.

**Comment by viosoft** [comment]
This is now available in [20190614](https://github.com/mips-open-ide/Releases/blob/master/v1.0.20190614%20Release%20Notes.md) release.
