### ISSUE TITLE
The Memory view did not work

### ISSUE THREAD

**Issue by arbing2014** [mips-open-ide/Releases#23]
Hi All,

It seems that the memory view did not work on my side. (window version). Please see the picture below: 
![memory_view](https://user-images.githubusercontent.com/6646354/57324794-305e3400-713b-11e9-96df-16c92a8416b6.jpg)

I'm not sure whether is because I didn't use in the correct way or not. 
Can you please help... Thank.

**Comment by tuanha-viosoft** [comment]
You need to add an address to display in the “Memory” view.
Refer https://github.com/mips-open-ide/Releases/wiki/Memory-Viewing
