### ISSUE TITLE
Can't start QEMU on IDE v1.0.20190417 on Ubuntu

### ISSUE THREAD

**Issue by kurt-wave** [mips-open-ide/Releases#24]
I installed the latest version of the MIPS Open IDE on my Ubuntu Linux machine:

MIPS OPEN IDE v1.0.20190417 (Updated Release - 17 APRIL, 2019)

The QEMU in this version won't start.  If I click on the icon to start QEMU from the IDE, and choose MIPS32R6, nothing appears to happen.  If I click on the "Bug" icon to debug my Linux program, I see the following message in the Console:

/home/kurt/MIPS Open IDE//bin/qemu/bin/qemu-system-mips: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

If I try starting QEMU from the command line, I get the same message:

kurt@ubuntu-rich:~/MIPS Open IDE$ ./bin/qemu/bin/qemu-system-mips -cpu /?

./bin/qemu/bin/qemu-system-mips: relocation error: /lib/x86_64-linux-gnu/libnss_files.so.2: symbol __libc_readline_unlocked, version GLIBC_PRIVATE not defined in file libc.so.6 with link time reference

I deleted this version of the IDE and re-installed the previous version.  The previous version still works.  I deleted the previous version and re-installed the new version.  The new version still fails.

Does this have anything to do with my version of Ubuntu?  I'm using Ubuntu 18.10.

Kurt

**Comment by xuanhoa9985-viosoft** [comment]
Hi Kurt,
QEMU from this: git://git.qemu-project.org/qemu.git is used, it was compiled for Ubuntu 16.04 and Ubuntu 18.04. It was not compiled for Ubuntu 18.10.
The QEMU will be replaced by the one from MIPS Toolchain, it is expected to work on Ubuntu 18.10 too.  We are working on it.

**Comment by tuanha-viosoft** [comment]
Switch to use qemu from toolchain now.
