### ISSUE TITLE
Can the QEMU to upgrade to version 4.0.0

### ISSUE THREAD

**Issue by arbing2014** [mips-open-ide/Releases#27]
Hi Viosoft Expert,

As the I would like to try to debug I6500 core with MSA, But I cannot find where to configure the qemu with I6500 core. I check and find the QEMU version 2 is used. 

However, now, the latest version of qemu is version 4. And it can support a great deal of MIPS CPU, So could you please think to upgrade the qemu to version 4.0.0

The CPU supported on version 4.0.0:    '4Kc', '4Km', '4KEcR1', '4KEmR1', '4KEc', '4KEm', '24Kc', '24KEc', '24Kf', '34Kf', '74Kf', 'M14K', 'M14Kc', 'P5600', 'mips32r6-generic', 'I7200', 'R4000', 'VR5432', '5Kc', '5Kf', '20Kc', '64R2-generic', '5KEc', '5KEf', 'I6400', 'I6500', 'Loongson-2E', 'Loongson-2F', 'mips64dspr2'

Thank you.

**Comment by tuanha-viosoft** [comment]
Hi @arbing2014 
We have the plan to use QEMU in MIPS toolchain in the future. We will consider to upgrade QEMU to the latest version when updating toolchain.

**Comment by kurt-wave** [comment]
Hi arbing2014,

Even though the QEMU in the MIPS Open IDE does not yet support the I6500 cpu, it does support the MIPS64R6-generic cpu.  I tried using this and I found that the MIPS64R6-generic cpu appears to support MSA instructions.  I just hacked a couple of MSA instructions into my C program, and they worked.  Here is what I see in the debugger:

![2019-05-21_13-13-08](https://user-images.githubusercontent.com/48976304/58127945-64ba0180-7bcb-11e9-9b79-d3dd3c9d1034.png)

To get the MIPS64R6-generic cpu when you debug, you need to edit the "Run Configuration" that corresponds to your Debug Configuration.  Here is a picture to show what I mean:

![2019-05-21_13-14-43](https://user-images.githubusercontent.com/48976304/58127918-54a22200-7bcb-11e9-97c5-c1f3753a935d.png)

As you can see, I modified the cpu name in the Arguments tab of the Run Configuration.

I have attached a zip file containing my test project.  You should be able to import it into the MIPS Open IDE.  This should show you how you can execute MSA instructions using the QEMU in the MIPS Open IDE.

Kurt
[msa-test.zip](https://github.com/mips-open-ide/Releases/files/3204376/msa-test.zip)

**Comment by arbing2014** [comment]
Hi Kurt, 
It is great to get your help.  I'm trying it now.  Thank you very much.

Can I have one more question: Do you known which MSA version current supported? we would like to try the the MSA on I6500.

Thanks again.

**Comment by kurt-wave** [comment]
Hi arbing2014,

There is only one version of MSA for MIPS64R6.  So an MSA program for the I6500 should be executable on the MIPS64R6-generic cpu in QEMU.

Kurt
