### ISSUE TITLE
Confusing info in release notes

### ISSUE THREAD

**Issue by viosoft** [mips-open-ide/Releases#3]
Step 2 of the installer shows the Release Notes.  I don't understand the line that says "Added new version Embedded and Embedded Linux support for MIPS".  What is Embedded vs Embedded Linux support?  For the same reason I don't know what it means where it says "The Embedded Edition doesn't work on Windows".  What Edition did I just install, Embedded or Embedded Linux?

After the installation is complete, this dialog pops up:

-- From Kurt

**Comment by tuanha-viosoft** [comment]
> Step 2 of the installer shows the Release Notes. I don't understand the line that says "Added new version Embedded and Embedded Linux support for MIPS". What is Embedded vs Embedded Linux support? For the same reason I don't know what it means where it says "The Embedded Edition doesn't work on Windows". What Edition did I just install, Embedded or Embedded Linux?

Standalone Embedded means Debugging with QEMU only.
Embedded Linux means Debugging with QEMU with RootFS and Kernel running.

The MIPS Open IDE had already supported both.
