### ISSUE TITLE
Where to install MIPS toolchain?

### ISSUE THREAD

**Issue by viosoft** [mips-open-ide/Releases#4]
No program group is created in the Start menu after install.  There is a desktop icon <for the IDE>

The setup video shows the user downloading 4 toolchains using Firefox.  But the video does not show the toolchains being unpacked or installed.  When I clicked on the links to download, that's all that happened.  I downloaded 2 separate .tar.gz toolchain files (which Windows renamed as .tar.tar files).  But they did not get unpacked.  The question is, where are the toolchains supposed to be installed?  And how is the user supposed to unpack and install the toolchains?  They are only provided as .tar.gz files, not executable installers.

On my Windows 7 PC, the IDE seems to know where my previously installed Codescape GNU Toolchains were installed (C:\Program Files\Imagination Technologies\Toolchains\.  But how does a new user know where to put the toolchains?

-- From Kirt

**Comment by tuanha-viosoft** [comment]
> No program group is created in the Start menu after install. There is a desktop icon

We will add it soon.

> The setup video shows the user downloading 4 toolchains using Firefox. But the video does not show the toolchains being unpacked or installed. When I clicked on the links to download, that's all that happened. I downloaded 2 separate .tar.gz toolchain files (which Windows renamed as .tar.tar files). But they did not get unpacked. The question is, where are the toolchains supposed to be installed? And how is the user supposed to unpack and install the toolchains? They are only provided as .tar.gz files, not executable installers.

> On my Windows 7 PC, the IDE seems to know where my previously installed Codescape GNU Toolchains were installed (C:\Program Files\Imagination Technologies\Toolchains. But how does a new user know where to put the toolchains?

The MIPS Open IDE finds the toolchains in the PATH environment variable. You can extract toolchain anywhere you want and set the path to **bin** folder of toolchain (ex: _C:\Users\viosoft\Downloads\mips-mti-elf\2018.09-03\bin_) to PATH.
https://www.computerhope.com/issues/ch000549.htm
