### ISSUE TITLE
Program output not shown on QEMU during debugging

### ISSUE THREAD

**Issue by viosoft** [mips-open-ide/Releases#5]
After I created and built my project, I followed the video and double clicked on the "MIPS Config" to create a new launch config.  My new config is named mips-img, but the new config in the video is named "mips-img Debug IMG LINUX".  

After I click Debug, I get the message "Guest has not initialized the display (yet)" on QEMU

This is not the same as the video, which shows Linux booting to a prompt in the QEMU window.  However, the debug launch continues.  It opens the Debug Perspective and it appears that the program is running in QEMU and has gotten to the breakpoint at main.  But nothing is ever printed in the QEMU window.

I am able to follow the steps shown in the video for debugging the program.  I can single step, view assembly, etc.

The video shows the debug session being terminated before the "return 0" statement in the program.  That seems strange to me.  I think you should be able to run the program all the way to the end and see the return value.  But if I let the program run to the end, I get a segmentation fault.  Here is what I see:

-- From Dinu

**Comment by tuanha-viosoft** [comment]
> After I click Debug, I get the message "Guest has not initialized the display (yet)" on QEMU

> This is not the same as the video, which shows Linux booting to a prompt in the QEMU window. However, the debug launch continues. It opens the Debug Perspective and it appears that the program is running in QEMU and has gotten to the breakpoint at main. But nothing is ever printed in the QEMU window.

We disabled the booting log of QEMU to make QEMU to boot faster.
When QEMU finishes booting, it will show the login screen.

> The video shows the debug session being terminated before the "return 0" statement in the program. That seems strange to me. I think you should be able to run the program all the way to the end and see the return value. But if I let the program run to the end, I get a segmentation fault. Here is what I see:

This issue is fixed in the release v1.0.20190324.
https://github.com/mips-open-ide/Releases

**Comment by kurt-wave** [comment]
The original entry in this ticket says "from Dinu", but it was actually copy/pasted from an email that I wrote.  I can verify that all issues that I raised in this ticket have been fixed in the release v1.0.20190324.  This ticket can be closed.  Thanks!
