### ISSUE TITLE
Single stepping takes 15-20 sec

### ISSUE THREAD

**Issue by viosoft** [mips-open-ide/Releases#6]
I cannot tell what type of customer or project this IDE is suitable for. I installed the Windows version and found my usual bare metal demo program for SEAD3 will compile but cannot be debugged. The error message that pops up is:

Error in final launch sequence

Failed to execute MI command:

-target-select remote localhost:1240

 

Error message from debugger back end:

localhost:1240: The system tried to join a drive to a directory on a joined drive.

localhost:1240: The system tried to join a drive to a directory on a joined drive.

 

I tried just creating a simple demo as shown in the sharepoint movie and found that for bare metal, only R2/R5 is supported (MTI tools) but R6 (IMG) is supported for linux apps. I thought the MIPS open program is specifically targeted to R6 ISA so this is not really suitable for startup code.

 

I did create the simple img-linux program, and could debug it with the only option available, qemu (no probes). The qemu window popped up as shown in the movie, but it simply displayed a message “Guest has not initialized the display (yet).”

I do not know if that affects the debug experience or not. Single step in the debugger took 15-20 seconds each with variable and disassembly windows open. It took a couple minutes to get to the breakpoint at main. That seems to be a bit long for most people to endure.

-- From Richard

**Comment by tuanha-viosoft** [comment]
MIPS R6 (IMG) is not supported for now and is removed from MIPS Open IDE.
This issue is fixed in the release v1.0.20190324.
https://github.com/mips-open-ide/Releases
