### ISSUE TITLE
Support on CentOS host

### ISSUE THREAD

**Issue by viosoft** [mips-open-ide/Releases#7]
I am also moving on to checking out the MIPS Open IDE on a Linux installation.  Is CentOS supported?  I’m using CentOS 6.6 and I’m having a problem with the IDE crashing.  Here is my Linux information:

 

bash-4.1$ cat /etc/redhat-release

CentOS release 6.6 (Final)

bash-4.1$ uname -a

Linux scgw05 2.6.32-504.23.4.el6.x86_64 #1 SMP Tue Jun 9 20:57:37 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

bash-4.1$

 

The install of the IDE seemed OK, and I was able to start the IDE and create the new project.  But when I try to open the main.c file for editing, it crashes the IDE.  I get this message in the window where I started the IDE:

 

java: cairo-misc.c:380: _cairo_operator_bounded_by_source: Assertion `NOT_REACHED' failed.

 

I tried using the Open With menu to choose the C/C++ Editor, the Text Editor, the System Editor, or the Default Editor.  But they all cause the IDE to crash as soon as I try to open my main.c file.  So I can’t go further with testing on CentOS 6 at this time.

**Comment by tuanha-viosoft** [comment]
I'll check it soon

**Comment by tuanha-viosoft** [comment]
Support CentOS in the release v1.0.20190409 (We tested on Ubuntu 16.04, Ubuntu 18.04, CentOS 7.6)

**Comment by tuanha-viosoft** [comment]
The MIPS Open IDE doesn't support CentOS 6 or below because it requires libc 2.14, but CentOS 6.x is using libc 2.12
