### ISSUE TITLE
Temporary breakpoint is listed in the breakpoint view

### ISSUE THREAD

**Issue by richardhilbig** [mips-open-ide/Releases#9]
Created new project with stop at main selected. Upon stopping, the temporary breakpoint was still shown in the breakpoint view. It was shown as a gdb temporary bkpt in the console. Clicking on the bkpt in the view resulted in an error message in the console, "No breakpoint number 1."

**Comment by tuanha-viosoft** [comment]
Hi @richardhilbig ,
Can you tell me which toolchain you were using and attach some images about the issues?

**Comment by richardhilbig** [comment]
mips-mti-elf-gcc -msoft-float -mips32r2 -mabi=32 -EL -Tuhi32.ld -o "simple-mips-mti-elf.elf" $(OBJS) $(USER_OBJS) $(LIBS)
C:\Program Files\Imagination Technologies\Toolchains\mips-mti-elf\2018.09-03\bin

![bkpt1](https://user-images.githubusercontent.com/48995747/55165257-58b14680-512a-11e9-9a44-5286caaac03d.PNG)

191,816 ~"The target is assumed to be little endian\n"
191,816 26^done
191,816 (gdb) 
191,818 27tbreak main

191,826 &"tbreak main\n"
191,827 ~"Temporary breakpoint 1 at 0x80200748: file ../src/main.c, line 8.\n"
191,827 =breakpoint-created,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x802007\
48",func="main",file="../src/main.c",fullname="C:\\Users\\richard.hilbig.MIPSTEC\\MIPS Open\\workspa\
ce\\simple-mips-mti-elf\\src\\main.c",line="8",thread-groups=["i1"],times="0",original-location="mai\
n"}
191,827 27^done
191,828 (gdb) 
191,828 &"\n"
191,828 ^done
191,828 (gdb) 
191,829 28continue

191,840 &"continue\n"
191,840 ~"Continuing.\n"
191,840 28^running
191,840 *running,thread-id="all"
191,840 (gdb) 
192,009 =breakpoint-modified,bkpt={number="1",type="breakpoint",disp="del",enabled="y",addr="0x80200\
748",func="main",file="../src/main.c",fullname="C:\\Users\\richard.hilbig.MIPSTEC\\MIPS Open\\worksp\
ace\\simple-mips-mti-elf\\src\\main.c",line="8",thread-groups=["i1"],times="1",original-location="ma\
in"}
192,013 ~"\nTemporary breakpoint "
192,014 ~"1, main (argc=2, argv=0x802fffb8) at ../src/main.c:8\n"
192,014 ~"8\t\tint a = 1;\n"
192,015 *stopped,reason="breakpoint-hit",disp="del",bkptno="1",frame={addr="0x80200748",func="main",\
args=[{name="argc",value="2"},{name="argv",value="0x802fffb8"}],file="../src/main.c",fullname="C:\\U\
sers\\richard.hilbig.MIPSTEC\\MIPS Open\\workspace\\simple-mips-mti-elf\\src\\main.c",line="8"},thre\
ad-id="1",stopped-threads="all"
192,015 **=breakpoint-deleted,id="1"
192,015 (gdb) 
192,032 &"\n"
192,032 ^done

If I disable the temp breakpoint in the view, nothing is reported in the gdb console.
If I create a new bkpt and disable it, then I see the creation and the disable event in the console.

594,313 57-break-insert -f "\"C:\\Users\\richard.hilbig.MIPSTEC\\MIPS Open\\workspace\\simple-mips-m\
ti-elf\\src\\main.c\":11"
594,322 57^done,bkpt={number="2",type="breakpoint",disp="keep",enabled="y",addr="0x80200768",func="m\
ain",file="../src/main.c",fullname="C:\\Users\\richard.hilbig.MIPSTEC\\MIPS Open\\workspace\\simple-\
mips-mti-elf\\src\\main.c",line="11",thread-groups=["i1"],times="0",original-location="C:\\Users\\ri\
chard.hilbig.MIPSTEC\\MIPS Open\\workspace\\simple-mips-mti-elf\\src\\main.c:11"}
594,322 (gdb) 
664,615 58-break-disable 2
664,619 58^done
664,619 (gdb)

**Comment by dzungdh-viosoft** [comment]
This issue was fixed in the release v1.0.20190403
